import Head from "next/head";
import Image from "next/image";
import PageTuto from "./PageTuto.jsx";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import UserNamePage from "./UserNamePage.jsx";
import HomePage from "./HomePage.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PageTuto />
        <UserNamePage />
        <HomePage />
      </main>
    </>
  );
}
